
'use server';

/**
 * @fileOverview Classifies all constituent sources of noise from an audio snippet.
 *
 * - classifyNoise - A function that classifies the noise sources.
 * - ClassifyNoiseInput - The input type for the classifyNoise function.
 * - ClassifyNoiseOutput - The return type for the classifyNoise function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'zod';

const ClassifyNoiseInputSchema = z.object({
  audioDataUri: z
    .string()
    .describe(
      "A short audio clip, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type ClassifyNoiseInput = z.infer<typeof ClassifyNoiseInputSchema>;

const NoiseClassificationSchema = z.object({
  name: z.string().describe('The name of the identified noise source (e.g., Traffic, Construction).'),
  description: z.string().describe('A brief description of the noise source.'),
  isHuman: z.boolean().describe('Set to true if the noise is generated by a human (e.g., speech, singing, crowd noise).'),
});

const ClassifyNoiseOutputSchema = z.array(NoiseClassificationSchema).describe('An array of all identified noise classifications, ordered from most to least prominent.');
export type ClassifyNoiseOutput = z.infer<typeof ClassifyNoiseOutputSchema>;

export async function classifyNoise(input: ClassifyNoiseInput): Promise<ClassifyNoiseOutput> {
  return classifyNoiseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'classifyNoisePrompt',
  input: {schema: ClassifyNoiseInputSchema},
  output: {schema: ClassifyNoiseOutputSchema},
  prompt: `You are an expert in audio analysis and noise pollution. Your task is to classify all the distinct sources of noise from the provided audio clip.

  Analyze the audio and identify all dominant sounds. Order them from most prominent to least prominent.
  For each sound, determine if it is generated by a human. For example, 'Human Chatter', 'Speech', 'Singing', 'Crowd', 'Laughter' are human-generated sounds. 'Traffic' or 'Wind' are not. Set the 'isHuman' field accordingly.

  Audio: {{media url=audioDataUri}}

  Provide the classification as a JSON array of objects, where each object has 'name', 'description', and 'isHuman' fields.
  Examples of noise sources: Traffic, Construction, Human Chatter, Wind, Music, Siren, Dog Barking.
  If the source is unclear or no distinct noise is detected, return an empty array or classify it as 'Unknown'.
  `,
});

const classifyNoiseFlow = ai.defineFlow(
  {
    name: 'classifyNoiseFlow',
    inputSchema: ClassifyNoiseInputSchema,
    outputSchema: ClassifyNoiseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
